version: "3.8"

services:
  db:
    container_name: issue_tracker_psql
    image: postgres:latest
    ports:
      - "${DB_EXPOSED_HTTP_PORT}:${DB_INTERNAL_HTTP_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
    volumes:
      - ./db/migrations/initial_schema.sql:/docker-entrypoint-initdb.d/initial_schema.sql
      - ./db/migrations/session_schema.sql:/docker-entrypoint-initdb.d/session_schema.sql
      - ./db/seeds/initial_seeds.sql:/docker-entrypoint-initdb.d/initial_seeds.sql

  api:
    container_name: issue_tracker_api
    build:
      context: ./
    ports:
      - "${API_EXPOSED_HTTP_PORT}:${API_INTERNAL_HTTP_PORT}"
    depends_on:
      - db
    volumes:
      - .:/app
      - exclude:/app/node_modules/
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_INTERNAL_HTTP_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
